<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
            array('id' => '1','menu_slug' => 'role','permission_key' => 'browse_role','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '2','menu_slug' => 'role','permission_key' => 'read_role','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '3','menu_slug' => 'role','permission_key' => 'add_role','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '4','menu_slug' => 'role','permission_key' => 'edit_role','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '5','menu_slug' => 'role','permission_key' => 'delete_role','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '6','menu_slug' => 'menu','permission_key' => 'browse_menu','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '7','menu_slug' => 'menu','permission_key' => 'read_menu','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '8','menu_slug' => 'menu','permission_key' => 'add_menu','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '9','menu_slug' => 'menu','permission_key' => 'edit_menu','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '10','menu_slug' => 'menu','permission_key' => 'delete_menu','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '11','menu_slug' => 'access_control','permission_key' => 'browse_access_control','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '12','menu_slug' => 'dashboard','permission_key' => 'browse_dashboard','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '13','menu_slug' => 'bread','permission_key' => 'browse_bread','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '14','menu_slug' => 'bread','permission_key' => 'read_bread','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '15','menu_slug' => 'bread','permission_key' => 'add_bread','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '16','menu_slug' => 'bread','permission_key' => 'edit_bread','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '17','menu_slug' => 'bread','permission_key' => 'delete_bread','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '18','menu_slug' => 'app_setting','permission_key' => 'browse_app_setting','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '19','menu_slug' => 'app_setting','permission_key' => 'read_app_setting','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '20','menu_slug' => 'app_setting','permission_key' => 'add_app_setting','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '21','menu_slug' => 'app_setting','permission_key' => 'edit_app_setting','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '22','menu_slug' => 'app_setting','permission_key' => 'delete_app_setting','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '23','menu_slug' => 'app_setting','permission_key' => 'logo_app_setting','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '24','menu_slug' => 'admin','permission_key' => 'browse_admin','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '25','menu_slug' => 'admin','permission_key' => 'read_admin','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '26','menu_slug' => 'admin','permission_key' => 'add_admin','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '27','menu_slug' => 'admin','permission_key' => 'edit_admin','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '28','menu_slug' => 'admin','permission_key' => 'delete_admin','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '29','menu_slug' => 'admin','permission_key' => 'change_email','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '30','menu_slug' => 'admin','permission_key' => 'change_password','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '31','menu_slug' => 'admin','permission_key' => 'change_status','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '32','menu_slug' => 'media','permission_key' => 'browse_media','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '33','menu_slug' => 'media','permission_key' => 'read_media','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '34','menu_slug' => 'media','permission_key' => 'add_media','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '35','menu_slug' => 'media','permission_key' => 'edit_media','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '36','menu_slug' => 'media','permission_key' => 'delete_media','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '37','menu_slug' => 'country','permission_key' => 'browse_country','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '38','menu_slug' => 'country','permission_key' => 'read_country','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '39','menu_slug' => 'country','permission_key' => 'add_country','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '40','menu_slug' => 'country','permission_key' => 'edit_country','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '41','menu_slug' => 'country','permission_key' => 'delete_country','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '42','menu_slug' => 'state','permission_key' => 'browse_state','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '43','menu_slug' => 'state','permission_key' => 'read_state','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '44','menu_slug' => 'state','permission_key' => 'add_state','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '45','menu_slug' => 'state','permission_key' => 'edit_state','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '46','menu_slug' => 'state','permission_key' => 'delete_state','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '47','menu_slug' => 'district','permission_key' => 'browse_district','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '48','menu_slug' => 'district','permission_key' => 'read_district','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '49','menu_slug' => 'district','permission_key' => 'add_district','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '50','menu_slug' => 'district','permission_key' => 'edit_district','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '51','menu_slug' => 'district','permission_key' => 'delete_district','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '52','menu_slug' => 'city','permission_key' => 'browse_city','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '53','menu_slug' => 'city','permission_key' => 'read_city','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '54','menu_slug' => 'city','permission_key' => 'add_city','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '55','menu_slug' => 'city','permission_key' => 'edit_city','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '56','menu_slug' => 'city','permission_key' => 'delete_city','created_at' => '2025-04-07 01:36:34','updated_at' => '2025-04-07 01:36:34'),
            array('id' => '57','menu_slug' => 'client','permission_key' => 'browse_client','created_at' => NULL,'updated_at' => NULL),
            array('id' => '58','menu_slug' => 'client','permission_key' => 'read_client','created_at' => NULL,'updated_at' => NULL),
            array('id' => '59','menu_slug' => 'client','permission_key' => 'add_client','created_at' => NULL,'updated_at' => NULL),
            array('id' => '60','menu_slug' => 'client','permission_key' => 'edit_client','created_at' => NULL,'updated_at' => NULL),
            array('id' => '61','menu_slug' => 'client','permission_key' => 'delete_client','created_at' => NULL,'updated_at' => NULL),
            array('id' => '62','menu_slug' => 'vendor','permission_key' => 'browse_vendor','created_at' => NULL,'updated_at' => NULL),
            array('id' => '63','menu_slug' => 'vendor','permission_key' => 'read_vendor','created_at' => NULL,'updated_at' => NULL),
            array('id' => '64','menu_slug' => 'vendor','permission_key' => 'add_vendor','created_at' => NULL,'updated_at' => NULL),
            array('id' => '65','menu_slug' => 'vendor','permission_key' => 'edit_vendor','created_at' => NULL,'updated_at' => NULL),
            array('id' => '66','menu_slug' => 'vendor','permission_key' => 'delete_vendor','created_at' => NULL,'updated_at' => NULL),
            array('id' => '67','menu_slug' => 'status','permission_key' => 'browse_status','created_at' => NULL,'updated_at' => NULL),
            array('id' => '68','menu_slug' => 'status','permission_key' => 'add_status','created_at' => NULL,'updated_at' => NULL),
            array('id' => '69','menu_slug' => 'status','permission_key' => 'edit_status','created_at' => NULL,'updated_at' => NULL),
            array('id' => '70','menu_slug' => 'category','permission_key' => 'add_category','created_at' => NULL,'updated_at' => NULL),
            array('id' => '71','menu_slug' => 'category','permission_key' => 'edit_category','created_at' => NULL,'updated_at' => NULL),
            array('id' => '72','menu_slug' => 'category','permission_key' => 'delete_category','created_at' => NULL,'updated_at' => NULL),
            array('id' => '73','menu_slug' => 'product','permission_key' => 'browse_product','created_at' => NULL,'updated_at' => NULL),
            array('id' => '74','menu_slug' => 'product','permission_key' => 'read_product','created_at' => NULL,'updated_at' => NULL),
            array('id' => '75','menu_slug' => 'product','permission_key' => 'add_product','created_at' => NULL,'updated_at' => NULL),
            array('id' => '76','menu_slug' => 'product','permission_key' => 'edit_product','created_at' => NULL,'updated_at' => NULL),
            array('id' => '77','menu_slug' => 'product','permission_key' => 'delete_product','created_at' => NULL,'updated_at' => NULL),
            array('id' => '80','menu_slug' => 'product_type','permission_key' => 'add_product_type','created_at' => NULL,'updated_at' => NULL),
            array('id' => '81','menu_slug' => 'product_type','permission_key' => 'edit_product_type','created_at' => NULL,'updated_at' => NULL),
            array('id' => '82','menu_slug' => 'product_type','permission_key' => 'delete_product_type','created_at' => NULL,'updated_at' => NULL),
            array('id' => '91','menu_slug' => 'material_inward','permission_key' => 'browse_material_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '92','menu_slug' => 'material_inward','permission_key' => 'read_material_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '93','menu_slug' => 'material_inward','permission_key' => 'add_material_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '94','menu_slug' => 'material_inward','permission_key' => 'edit_material_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '95','menu_slug' => 'material_inward','permission_key' => 'delete_material_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '96','menu_slug' => 'material_order','permission_key' => 'browse_material_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '97','menu_slug' => 'material_order','permission_key' => 'read_material_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '98','menu_slug' => 'material_order','permission_key' => 'add_material_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '99','menu_slug' => 'material_order','permission_key' => 'edit_material_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '100','menu_slug' => 'material_order','permission_key' => 'delete_material_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '101','menu_slug' => 'item','permission_key' => 'browse_item','created_at' => NULL,'updated_at' => NULL),
            array('id' => '102','menu_slug' => 'item','permission_key' => 'read_item','created_at' => NULL,'updated_at' => NULL),
            array('id' => '103','menu_slug' => 'item','permission_key' => 'add_item','created_at' => NULL,'updated_at' => NULL),
            array('id' => '104','menu_slug' => 'item','permission_key' => 'edit_item','created_at' => NULL,'updated_at' => NULL),
            array('id' => '105','menu_slug' => 'cylinder_inward','permission_key' => 'browse_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '106','menu_slug' => 'cylinder_inward','permission_key' => 'read_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '107','menu_slug' => 'cylinder_inward','permission_key' => 'add_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '108','menu_slug' => 'cylinder_inward','permission_key' => 'edit_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '109','menu_slug' => 'cylinder_inward','permission_key' => 'delete_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '110','menu_slug' => 'cylinder_inward','permission_key' => 'cancel_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '111','menu_slug' => 'purchase_order','permission_key' => 'browse_purchase_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '112','menu_slug' => 'purchase_order','permission_key' => 'read_purchase_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '113','menu_slug' => 'purchase_order','permission_key' => 'add_purchase_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '114','menu_slug' => 'purchase_order','permission_key' => 'edit_purchase_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '115','menu_slug' => 'purchase_order','permission_key' => 'delete_purchase_order','created_at' => NULL,'updated_at' => NULL),
            array('id' => '116','menu_slug' => 'order_sheet','permission_key' => 'browse_order_sheet','created_at' => NULL,'updated_at' => NULL),
            array('id' => '117','menu_slug' => 'order_sheet','permission_key' => 'read_order_sheet','created_at' => NULL,'updated_at' => NULL),
            array('id' => '118','menu_slug' => 'order_sheet','permission_key' => 'add_order_sheet','created_at' => NULL,'updated_at' => NULL),
            array('id' => '119','menu_slug' => 'order_sheet','permission_key' => 'edit_order_sheet','created_at' => NULL,'updated_at' => NULL),
            array('id' => '120','menu_slug' => 'order_sheet','permission_key' => 'delete_order_sheet','created_at' => NULL,'updated_at' => NULL),
            array('id' => '121','menu_slug' => 'dye','permission_key' => 'browse_dye','created_at' => NULL,'updated_at' => NULL),
            array('id' => '122','menu_slug' => 'dye','permission_key' => 'read_dye','created_at' => NULL,'updated_at' => NULL),
            array('id' => '123','menu_slug' => 'dye','permission_key' => 'add_dye','created_at' => NULL,'updated_at' => NULL),
            array('id' => '124','menu_slug' => 'dye','permission_key' => 'edit_dye','created_at' => NULL,'updated_at' => NULL),
            array('id' => '125','menu_slug' => 'dye','permission_key' => 'delete_dye','created_at' => NULL,'updated_at' => NULL),
            array('id' => '126','menu_slug' => 'dye_lock_type','permission_key' => 'read_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
            array('id' => '127','menu_slug' => 'dye_lock_type','permission_key' => 'add_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
            array('id' => '128','menu_slug' => 'dye_lock_type','permission_key' => 'edit_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
            array('id' => '129','menu_slug' => 'dye_lock_type','permission_key' => 'delete_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
            array('id' => '130','menu_slug' => 'processing','permission_key' => 'browse_processing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '131','menu_slug' => 'processing','permission_key' => 'read_processing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '132','menu_slug' => 'processing','permission_key' => 'add_processing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '133','menu_slug' => 'processing','permission_key' => 'edit_processing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '134','menu_slug' => 'processing','permission_key' => 'delete_processing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '135','menu_slug' => 'job_card','permission_key' => 'browse_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '136','menu_slug' => 'job_card','permission_key' => 'read_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '137','menu_slug' => 'job_card','permission_key' => 'add_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '138','menu_slug' => 'job_card','permission_key' => 'edit_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '139','menu_slug' => 'job_card','permission_key' => 'delete_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '140','menu_slug' => 'firm','permission_key' => 'browse_firm','created_at' => NULL,'updated_at' => NULL),
            array('id' => '141','menu_slug' => 'firm','permission_key' => 'read_firm','created_at' => NULL,'updated_at' => NULL),
            array('id' => '142','menu_slug' => 'firm','permission_key' => 'add_firm','created_at' => NULL,'updated_at' => NULL),
            array('id' => '143','menu_slug' => 'firm','permission_key' => 'edit_firm','created_at' => NULL,'updated_at' => NULL),
            array('id' => '144','menu_slug' => 'job_card','permission_key' => 'add_details_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '150','menu_slug' => 'job_card','permission_key' => 'canceled_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '157','menu_slug' => 'department','permission_key' => 'read_department','created_at' => NULL,'updated_at' => NULL),
            array('id' => '158','menu_slug' => 'department','permission_key' => 'add_department','created_at' => NULL,'updated_at' => NULL),
            array('id' => '159','menu_slug' => 'department','permission_key' => 'edit_department','created_at' => NULL,'updated_at' => NULL),
            array('id' => '160','menu_slug' => 'material_issue','permission_key' => 'browse_material_issue','created_at' => NULL,'updated_at' => NULL),
            array('id' => '161','menu_slug' => 'material_issue','permission_key' => 'read_material_issue','created_at' => NULL,'updated_at' => NULL),
            array('id' => '162','menu_slug' => 'material_issue','permission_key' => 'add_material_issue','created_at' => NULL,'updated_at' => NULL),
            array('id' => '163','menu_slug' => 'material_issue','permission_key' => 'edit_material_issue','created_at' => NULL,'updated_at' => NULL),
            array('id' => '164','menu_slug' => 'material_issue','permission_key' => 'delete_material_issue','created_at' => NULL,'updated_at' => NULL),
            array('id' => '165','menu_slug' => 'carton_rate','permission_key' => 'browse_carton_rate','created_at' => NULL,'updated_at' => NULL),
            array('id' => '166','menu_slug' => 'carton_rate','permission_key' => 'edit_carton_rate','created_at' => NULL,'updated_at' => NULL),
            array('id' => '167','menu_slug' => 'operator','permission_key' => 'browse_operator','created_at' => NULL,'updated_at' => NULL),
            array('id' => '168','menu_slug' => 'operator','permission_key' => 'read_operator','created_at' => NULL,'updated_at' => NULL),
            array('id' => '169','menu_slug' => 'operator','permission_key' => 'add_operator','created_at' => NULL,'updated_at' => NULL),
            array('id' => '170','menu_slug' => 'operator','permission_key' => 'edit_operator','created_at' => NULL,'updated_at' => NULL),
            array('id' => '171','menu_slug' => 'operator','permission_key' => 'delete_operator','created_at' => NULL,'updated_at' => NULL),
            array('id' => '172','menu_slug' => 'paper_cutting','permission_key' => 'browse_paper_cutting','created_at' => NULL,'updated_at' => NULL),
            array('id' => '173','menu_slug' => 'paper_cutting','permission_key' => 'edit_paper_cutting','created_at' => NULL,'updated_at' => NULL),
            array('id' => '174','menu_slug' => 'printing','permission_key' => 'browse_printing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '175','menu_slug' => 'printing','permission_key' => 'edit_printing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '176','menu_slug' => 'coating','permission_key' => 'browse_coating','created_at' => NULL,'updated_at' => NULL),
            array('id' => '177','menu_slug' => 'coating','permission_key' => 'edit_coating','created_at' => NULL,'updated_at' => NULL),
            array('id' => '178','menu_slug' => 'leafing','permission_key' => 'browse_leafing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '179','menu_slug' => 'leafing','permission_key' => 'edit_leafing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '180','menu_slug' => 'embossing','permission_key' => 'browse_embossing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '181','menu_slug' => 'embossing','permission_key' => 'edit_embossing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '182','menu_slug' => 'lamination','permission_key' => 'browse_lamination','created_at' => NULL,'updated_at' => NULL),
            array('id' => '183','menu_slug' => 'lamination','permission_key' => 'edit_lamination','created_at' => NULL,'updated_at' => NULL),
            array('id' => '184','menu_slug' => 'spot_uv','permission_key' => 'browse_spot_uv','created_at' => NULL,'updated_at' => NULL),
            array('id' => '185','menu_slug' => 'spot_uv','permission_key' => 'edit_spot_uv','created_at' => NULL,'updated_at' => NULL),
            array('id' => '186','menu_slug' => 'dye_cutting','permission_key' => 'browse_dye_cutting','created_at' => NULL,'updated_at' => NULL),
            array('id' => '187','menu_slug' => 'dye_cutting','permission_key' => 'edit_dye_cutting','created_at' => NULL,'updated_at' => NULL),
            array('id' => '188','menu_slug' => 'pasting','permission_key' => 'browse_pasting','created_at' => NULL,'updated_at' => NULL),
            array('id' => '189','menu_slug' => 'pasting','permission_key' => 'edit_pasting','created_at' => NULL,'updated_at' => NULL),
            array('id' => '190','menu_slug' => 'warehouse','permission_key' => 'browse_warehouse','created_at' => NULL,'updated_at' => NULL),
            array('id' => '191','menu_slug' => 'warehouse','permission_key' => 'edit_warehouse','created_at' => NULL,'updated_at' => NULL),
            array('id' => '192','menu_slug' => 'item_for_billing','permission_key' => 'browse_item_for_billing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '193','menu_slug' => 'item_for_billing','permission_key' => 'read_item_for_billing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '194','menu_slug' => 'billing','permission_key' => 'browse_billing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '195','menu_slug' => 'billing','permission_key' => 'read_billing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '196','menu_slug' => 'billing','permission_key' => 'add_billing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '197','menu_slug' => 'billing','permission_key' => 'edit_billing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '198','menu_slug' => 'billing','permission_key' => 'delete_billing','created_at' => NULL,'updated_at' => NULL),
            array('id' => '199','menu_slug' => 'store','permission_key' => 'add_store','created_at' => NULL,'updated_at' => NULL),
            array('id' => '200','menu_slug' => 'store','permission_key' => 'edit_store','created_at' => NULL,'updated_at' => NULL),
            array('id' => '201','menu_slug' => 'store','permission_key' => 'browse_store','created_at' => NULL,'updated_at' => NULL),
            array('id' => '204','menu_slug' => 'item','permission_key' => 'mfg_mkdt_item','created_at' => NULL,'updated_at' => NULL),
            array('id' => '209','menu_slug' => 'reel_inward','permission_key' => 'browse_reel_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '210','menu_slug' => 'reel_inward','permission_key' => 'read_reel_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '211','menu_slug' => 'reel_inward','permission_key' => 'add_reel_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '212','menu_slug' => 'reel_inward','permission_key' => 'edit_reel_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '213','menu_slug' => 'reel_inward','permission_key' => 'delete_reel_inward','created_at' => NULL,'updated_at' => NULL),
            array('id' => '214','menu_slug' => 'reel_job_card','permission_key' => 'browse_reel_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '215','menu_slug' => 'reel_job_card','permission_key' => 'read_reel_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '216','menu_slug' => 'reel_job_card','permission_key' => 'add_reel_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '217','menu_slug' => 'reel_job_card','permission_key' => 'edit_reel_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '218','menu_slug' => 'reel_job_card','permission_key' => 'delete_reel_job_card','created_at' => NULL,'updated_at' => NULL),
            array('id' => '219','menu_slug' => 'reel_conversion','permission_key' => 'browse_reel_conversion','created_at' => NULL,'updated_at' => NULL),
            array('id' => '220','menu_slug' => 'reel_conversion','permission_key' => 'read_reel_conversion','created_at' => NULL,'updated_at' => NULL),
            array('id' => '221','menu_slug' => 'reel_conversion','permission_key' => 'add_reel_conversion','created_at' => NULL,'updated_at' => NULL),
            array('id' => '222','menu_slug' => 'reel_conversion','permission_key' => 'edit_reel_conversion','created_at' => NULL,'updated_at' => NULL),
            array('id' => '223','menu_slug' => 'reel_conversion','permission_key' => 'delete_reel_conversion','created_at' => NULL,'updated_at' => NULL)
        ]);
    }
}
