<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('role_permissions')->insert([
            array('role_id' => '1','permission_key' => 'add_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_app_setting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_bread','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_category','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_city','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_client','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_country','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_department','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_details_job_card','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_district','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_dye','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_firm','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_item','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_job_card','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_material_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_material_issue','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_material_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_media','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_menu','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_operator','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_order_sheet','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_processing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_product','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_product_type','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_purchase_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_role','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_state','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_status','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'add_vendor','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_access_control','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_app_setting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_bread','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_carton_rate','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_city','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_client','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_coating','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_country','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_dashboard','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_district','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_dye','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_dye_cutting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_embossing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_firm','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_item','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_job_card','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_lamination','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_leafing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_material_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_material_issue','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_material_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_media','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_menu','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_operator','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_order_sheet','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_paper_cutting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_pasting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_printing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_processing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_product','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_purchase_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_role','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_spot_uv','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_state','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_status','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_vendor','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'browse_warehouse','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'cancel_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'canceled_job_card','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'change_email','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'change_password','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'change_status','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_app_setting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_bread','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_category','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_city','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_client','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_country','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_district','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_dye','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_job_card','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_material_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_material_issue','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_material_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_media','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_menu','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_operator','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_order_sheet','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_processing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_product','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_product_type','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_purchase_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_role','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_state','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'delete_vendor','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_app_setting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_bread','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_carton_rate','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_category','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_city','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_client','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_coating','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_country','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_department','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_district','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_dye','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_dye_cutting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_embossing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_firm','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_item','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_job_card','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_lamination','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_leafing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_material_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_material_issue','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_material_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_media','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_menu','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_operator','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_order_sheet','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_paper_cutting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_pasting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_printing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_processing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_product','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_product_type','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_purchase_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_role','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_spot_uv','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_state','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_status','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_vendor','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'edit_warehouse','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'logo_app_setting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_app_setting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_bread','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_city','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_client','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_country','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_cylinder_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_department','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_district','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_dye','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_dye_lock_type','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_firm','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_item','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_job_card','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_material_inward','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_material_issue','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_material_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_media','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_menu','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_operator','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_order_sheet','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_processing','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_product','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_purchase_order','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_role','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_state','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '1','permission_key' => 'read_vendor','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '2','permission_key' => 'browse_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '2','permission_key' => 'browse_dashboard','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '2','permission_key' => 'browse_setting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '2','permission_key' => 'edit_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '2','permission_key' => 'read_admin','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '3','permission_key' => 'browse_dashboard','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '4','permission_key' => 'browse_dashboard','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '5','permission_key' => 'browse_dashboard','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '5','permission_key' => 'browse_paper_cutting','created_at' => NULL,'updated_at' => NULL),
  array('role_id' => '5','permission_key' => 'edit_paper_cutting','created_at' => NULL,'updated_at' => NULL)
        ]);
    }
}
